### ISSUE TITLE
Remove monkey patch of `_get_title_cache` function

### ISSUE THREAD

**Issue by zkne** [django-cms/djangocms-versioning#235]
Monkey pathing of the [_get_title_cache](https://github.com/divio/djangocms-versioning/blob/master/djangocms_versioning/monkeypatch/page.py#L28) can be removed when the [issue](https://github.com/django-cms/django-cms/issues/7099) is resolved for version 4 of DjangoCMS.

**Comment by Aiky30** [comment]
Confirmed, the issue above is fixed by the monkey patch in versioning, it can be moved to the core of the CMS for v4. This will add a dependancy on versions so important that this is done correctly i.e. it is removed from versioning and added to the CMS at the same time.

**Comment by Aiky30** [comment]
The release of djangocms-versioning will be directly related to a specific version of django-cms
