### ISSUE TITLE
CMS Icons CSS

### ISSUE THREAD

**Issue by marksweb** [django-cms/djangocms-versioning#324]
The admin references the [now] removed `cms.icons.css` file.

https://github.com/django-cms/djangocms-versioning/blob/1e8a48c5a39ef4ab498f4378f92ec1f164745ef8/djangocms_versioning/admin.py#L218

https://github.com/django-cms/django-cms/tree/release/4.1.x/cms/static/cms/css/4.1.0rc1

**Comment by fsbraun** [comment]
It was actually not present in the 4.1rc1 yet. Can you try verisioning from this branch: https://github.com/django-cms/djangocms-versioning/tree/support/4.1rc ?

**Comment by marksweb** [comment]
That seems to have resolved it 👍
