### ISSUE TITLE
Confusing statement in `djangocms_versioning/admin.py`

### ISSUE THREAD

**Issue by jrief** [django-cms/djangocms-versioning#382]
This statement is confusing
https://github.com/django-cms/djangocms-versioning/blob/a70c194c27c5aadb58f07e42309613ca7952daa8/djangocms_versioning/admin.py#L974
because `redirect_url` always is `None`.

**Comment by fsbraun** [comment]
Agree. This is a bug. Line 972 needs to go. In case the published content does not have an absolute url, `redirect_url` then will point to the preview endpoint, which must exist.
