### ISSUE TITLE
Unpublishing a page from the sidebar does not close the sidebar

### ISSUE THREAD

**Issue by jrief** [django-cms/djangocms-versioning#383]
How to reproduce:

* Navigate to a published CMS page.
* From the CMS toolbar, open the page versioning menu. This opens an side frame containing a list of page content versions.
* Locate the row where state is published.
* Click on the button with the stroked antenna labled "Unpublish".
* Inside the current side frame, a confirmation dialog appears. Click on the "Yes, I'm sure" button.
* The current side frame does not close and the spinning wheel rotates forever. In order to close the that side frame, the user must click on the close button on its upper right.

Extra observations I made:
When clicking on the "Preview", "Publish" or "Revert" button in the list of page content versions, the click-event-listener in `/static/cms/js/admin/actions.js` is called which in turn calls the function `closeSideFrame()`. On the other side, unpublishing a page first renders a confirmation dialog. But here the "Yes, I'm sure" button is not connected to any event handler. Hence the
function `closeSideFrame()` is never called, leaving the side frame open forever.

I believe that the "Yes, I'm sure" button just requires one of the additional CSS classes `js-action`, `cms-js-edit-btn` or `cms-actions-dropdown-menu-item-anchor`,  in order to connect that event handler. Which classes should I use and is this the intended behaviour to close the side frame after clicking on that button?

**Comment by fsbraun** [comment]
Fixed in #386
