### ISSUE TITLE
Clicking on "Unlock"-button, sometimes shows page "404 - Not Found"

### ISSUE THREAD

**Issue by jrief** [django-cms/djangocms-versioning#384]
How to reproduce:

* Enable locking for the site (`DJANGOCMS_VERSIONING_LOCK_VERSIONS = True`).
* Someone else edits a page and publishes that page.
* Then he edits that page again, but he does not publish it. This keeps the page locked by him.
* I open the published page with the toolbar enabled.
* On the right, now there is a button named "Unlock".
* If I click on that button, error "404 - Not Found" is raised.

After analizing this, it turns out that the link behind the "Unlock"-button points onto the published page. This then results in the [404 - Not Found](https://github.com/django-cms/djangocms-versioning/blob/a70c194c27c5aadb58f07e42309613ca7952daa8/djangocms_versioning/admin.py#L1252) exception.

Unlocking a page can also be performed in the Versioning Admin List View. Here a list of page versions is rendered, but only the current version with `state=DRAFT` offers an unlock button. And from here, unlocking works as intended.

By applying this [patch](https://github.com/jrief/djangocms-versioning/commit/44c1a75a2ce666b49f22d91b3fb8c4688c848148), unlocking a page should work as expected. However, I'm unsure if this is the right approach.

**Comment by fsbraun** [comment]
@jrief Just for clarification: The button should not be shown on the published page, right?
