### ISSUE TITLE
[BUG] Adding a plugin to an apphooked page as admin raises permission error

### ISSUE THREAD

**Issue by aacimov** [django-cms/djangocms-versioning#394]
## Description

I have an AppHooked application with namespaced URL configuration (each AppHook represents different Product category and Category is my namespace). 

Since I want to be able to add plugins to the AppHooked page placeholders there is no default List view shown on the AppHooked page but instead I made a CMS Plugin named Products list which routes customers to product's detail page with the detail URL with namespaced URL respectively.

On my first AppHooked page (_Serial production_) everything works as expected, added a Product list CMS plugin and it works. On my other AppHooked page (_Hand made production_) when I try adding the same plugin it raises the error saying `You don't have permission to add plugin` but I am logged in as an admin. No other plugin can be added to the same placeholder as well. It also reflects to the first AppHooked page where the plugin is added. I also cannot edit the current plugin (Product list).

## Steps to reproduce

1. Create two pages (e.g. Page 1 and Page 2)
2. Add the same AppHook with different namespaced configs (AppHook Products with configs Config 1 and Config 2) to Page 1 and Page 2 respectively
3. Add a custom made CMS Plugin showing the list of products (Product list) to Page 1 - works well
4. Try adding the same custom made CMS Plugin (Product list) to Page 2
5. Permission error raised in the plugin modal window
6. Since this point any other plugin (e.g. TextPlugin) added to any of the stated AppHooked pages does not work raising the permission error while same issue raising when trying to edit a successfully added Product list plugin (step 3.)

## Expected behaviour

Plugins should not raise the permission error since logged in as an admin user. Plugins should be added with no errors.

## Additional information (CMS/Python/Django versions)

- Django 4.2.10
- Django CMS 4.1.0
- Django Treebeard 4.7.1
- Python 3.10
- MySQL 8.0.34 (utf8mb4_general_ci collation)

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@aacimov Order should not matter. I've moved this, since it seems to depend on versioning. I think you're redirected to a published/non-editable version of the `PageContent`. Can you find out what triggers the redirect? 

I frequently run my test systems on the latest development branches. For the sake of testing it: Can you install the latest develop branches:
* `pip install git+https://github.com/django-cms/django-cms@develop-4`
* `pip install git+https://github.com/django-cms/djangocms-versioning@master`

**Comment by aacimov** [comment]
@fsbraun sorry for the delay. Installed latest, still the same permisson error while adding plugins.

**Comment by aacimov** [comment]
@fsbraun I did not manage to find where the redirect happens so far. Since it is very much likely connected to djangocms-versioning could you point me in a direction perhaps? It would be helpful.

Tnx

**Comment by fsbraun** [comment]
@aacimov Can we schedule a zoom meeting or google meet to look at this together some time next week? PM me on Slack or Discord.

**Comment by fsbraun** [comment]
Will be fixed with django CMS 4.1.1

**Comment by aacimov** [comment]
Just had an extra issue regarding this saying - when trying to delete the record:

Deleting post 'Test post' would result in the deletion of the associated objects, but you do not have privileges to delete the specified objects:

placeholder

**Comment by fsbraun** [comment]
Try doing this with the english admin. Should be fixed in 4.1.1

**Comment by aacimov** [comment]
> Try doing this with the english admin. Should be fixed in 4.1.1

Just tried, same error.

**Comment by aacimov** [comment]
Installed - still the same unfortunately.

**Comment by fsbraun** [comment]
Hm. I fear that's not versioning-related. What happens if you remove these lines:
https://github.com/django-cms/django-cms/blob/4e7f24f2847846b3770e086068ff729961b2c450/cms/admin/placeholderadmin.py#L200-L202

**Comment by fsbraun** [comment]
The more I look into the code base the more I think this is a bug. Can you raise it in the django-cms repo?
