### ISSUE TITLE
Django-FSM archived: use django-viewflow instead.

### ISSUE THREAD

**Issue by joshyu** [django-cms/djangocms-versioning#400]
Hi team,

Yesterday [django-fsm](https://github.com/viewflow/django-fsm) released a new version **3.0.0** and announced that django-fsm is archived,  we should use [django-viewflow](https://github.com/viewflow/viewflow) instead.

**Comment by fsbraun** [comment]
@joshyu Thanks for pointing this out. We might want to consider dropping the dependency altogether. It's only a few lines of code.   @marksweb @Aiky30

**Comment by marksweb** [comment]
Someone's turned FSM into a cash cow sass product by the looks of it.

Will try to find time to look at this later.

**Comment by fsbraun** [comment]
I could imagine bundling the FSM functionality and versioning's conditions framework both into a small package for easier reuse, maybe even in the core - a bit like classy tags (django-conditions?). 

I can imagine a decent amount of improvement in readability.

**Comment by rolandf** [comment]
And the other issue is the license. I like Django/Django cms because their license allow me to build a business around it. I tend to avoid viral licenses.

**Comment by marksweb** [comment]
Quite like Fabian's idea of `django-conditions`. 👍

**Comment by jrief** [comment]
There is a fork of django-fsm: https://github.com/pfouque/django-fsm-2 which seems to be maintained.

I am **strictly against using django-viewflow** for the very simple reason, that it is not compatible with MIT/BSD/Apache - licensed software.
