### ISSUE TITLE
Permission denied is raised, although user has permission to edit the page

### ISSUE THREAD

**Issue by jrief** [django-cms/djangocms-versioning#409]
This happens in CMS4 branch `develop-4` (`650f31a80f9c3a579d40f201477f546ca663e88e`) in combination with djangocms-versioning (adce88065509c84212e432c41c05a121c246ed1f also latest).

In some situations a permission denied exception is raised, although the user has permission to edit that page. This happens when the user attempts to accessing the page settings editor.

### How to reproduce:

* Take a page with at least two versions.
* In Django admin, open the page versioning list view, ie. the URL shall be something like: `/en/admin/djangocms_versioning/pagecontentversion/?page=8943&language=en`. Replace `page=…` against a valid Page-ID.
* If there is at least one draft version of the page, **this error does not occur** – you can test by clicking into the breadcrumb onto the element preceding "Versions".
* Now remove the draft version for that page by clicking onto the trash symbol and confirm.
* The URL should be the same as before. In the list view of versions there should only be versions in state "published", "unpublished" and "archived".
* Now click onto the breadcrumb into the element preceding "Versions".
* This raises a permission denied exception.

### Expected behaviour

A user does not expect a permission denied exception, since he has permissions to edit the page.

**Comment by fsbraun** [comment]
Does the permission denied message also appear if you click on the settings icon in the page tree if there is no draft version of the page?
<img width="42" alt="image" src="https://github.com/django-cms/djangocms-versioning/assets/16904477/1ccda45c-6dba-4707-b555-8e1203c64b48">

**Comment by fsbraun** [comment]
Found the issue:
* django CMS core does not provide a `has_view_permission` for the page content's admin class
* The `has_change_permission` is overwritten to account for publishing status
* As a result, only the overwritten permission is applied - also to viewing the page settings
PAtch is coming up

**Comment by jrief** [comment]
> Does the permission denied message also appear if you click on the settings icon in the page tree if there is no draft version of the page? <img alt="image" width="42" src="https://private-user-images.githubusercontent.com/16904477/330581409-1ccda45c-6dba-4707-b555-8e1203c64b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MjE2NjcsIm5iZiI6MTcxNTcyMTM2NywicGF0aCI6Ii8xNjkwNDQ3Ny8zMzA1ODE0MDktMWNjZGE0NWMtNmRiYS00NzA3LWI1NTUtOGUxMjAzYzY0YjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDIxMTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYWZjYTU4OWVmZmFlM2NjNjQwZWMwYjFmZTlmODM0MmIyYzZiNTc0OGI5NWQ5ZWNhOTYxZWMxMmM0MjBiMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WatiQHeeSSEycdc27E66qiTv2RbEgoBxAIa5rG-duJ4">

Yes, in the page tree view I can reproduce this by clicking on the "page settings" icon.

**Comment by jrief** [comment]
This pull request fixes the problem:
https://github.com/django-cms/django-cms/pull/7921
